# Generated by Django 5.2 on 2025-05-06 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='user',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='user',
            new_name='staff',
        ),
    ]
