# Generated by Django 5.2 on 2025-05-08 10:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_remove_appointment_service_appointment_services'),
        ('schedule', '0016_remove_calendarrelation_cal_rel_content_obj_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='_end_time',
            field=models.DateTimeField(db_column='end_time', default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.calendar'),
        ),
    ]
