# Generated by Django 5.2 on 2025-05-12 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_service_duration_alter_staff_calendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='_end_time',
            field=models.DateTimeField(blank=True, db_column='end_time', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(help_text='e.g., 0:15:00 for 15 minutes'),
        ),
    ]
