# Generated by Django 5.2 on 2025-05-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0007_alter_appointment_options_alter_staff_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
