# Generated by Django 5.2 on 2025-05-16 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0008_staff_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='is_staff',
        ),
    ]
